CFLAGS=-Wall -g

object = for_loop hello sizeof \
	formatted_printing

all:
	cc for_loop.c -o for_loop
	cc hello.c -o hello
	cc sizeof.c -o sizeof
	cc formatted_printing formatted_printing.c

clean:
	rm -f $(object)
