CFLAGS=-Wall -g

all:
	cc bubbleSort.c		-o bubbleSort
	cc insertionSort.c	-o insertionSort
	cc mergeSort.c		-o mergeSort
	cc quickSort.c 		-o quickSort
	cc selectionSort.c	-o selectionSort
	cc shellSort.c		-o shellSort
clean:
	rm -f bubbleSort
	rm -f insertionSort
	rm -f mergeSort
	rm -f quickSort
	rm -f selectionSort
	rm -f shellSort
